version: '3.4'

services:
  cis.webapp:
    image: ${DOCKER_REGISTRY-}ciswebapp
    build:
      context: .
      dockerfile: CIS.WebApp/Dockerfile
    networks:
      - cis-network

  cis.integration:
    image: ${DOCKER_REGISTRY-}cisintegration
    build:
      context: .
      dockerfile: CIS.Integration/Dockerfile
    networks:
      - cis-network

networks:
  cis-network:
    driver: bridge
