// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CIS.DataAccess.Legacy;

public partial class Bestillingsforslag
{
    public decimal Id { get; set; }

    public DateTime? Dato { get; set; }

    public int? But { get; set; }

    public string Butikknavn { get; set; }

    public int? VareId { get; set; }

    public string VarenrLev { get; set; }

    public string Varebeskrivelse { get; set; }

    public int? Lager { get; set; }

    public int? SalgsProg { get; set; }

    public int? Behov { get; set; }

    public int? Dul { get; set; }
}