// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CIS.DataAccess.Legacy;

public partial class ButikkTemp
{
    public int? Butikknr { get; set; }

    public int? Konsept { get; set; }
}