// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CIS.Application.Legacy;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace CIS.Application.Legacy
{
    public partial interface ISWNDistroProcedures
    {
        Task<List<beregnetLagerResult>> beregnetLagerAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<beregnlagerResult>> beregnlagerAsync(DateTime? dato, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<FilExport_Distro_2020Result>> FilExport_Distro_2020Async(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<FilExport_Distro_2020_EnkeltOrdreResult>> FilExport_Distro_2020_EnkeltOrdreAsync(string ordreRef, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<hentButikkOrdreResult>> hentButikkOrdreAsync(int? butikknr, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<hentVaretellingsDifferResult>> hentVaretellingsDifferAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ImportLagerResult>> ImportLagerAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ImportPakkseddelResult>> ImportPakkseddelAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ImportSalgstallResult>> ImportSalgstallAsync(string filnavn, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<lagerberegningResult>> lagerberegningAsync(int? butikknr, int? periodeRC, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<LagerstatusResult>> LagerstatusAsync(DateTime? datoNaa, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> leggtilnyevarerAsync(string varenrlev, string eankode, string beskrivelse, decimal? innprisCS, decimal? innprisRC, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<LeggtilNyOrdreResult>> LeggtilNyOrdreAsync(int? butikknr, int? vareID, int? antall, string ordreID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> leggtilNyttKundenrAsync(int? butikknr, int? kundenr, DateTime? datofra, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<LesInnOrdrefilerFraButikkResult>> LesInnOrdrefilerFraButikkAsync(string filnavn, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<oppdaterLagerdataResult>> oppdaterLagerdataAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> oppdaterLiggendeOrdreAsync(int? id, int? antall, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ordreFordelingÅpningsordreResult>> ordreFordelingÅpningsordreAsync(int? butikknr, string varenrLev, int? antall, string ordreRef, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ordreFraNettButikkResult>> ordreFraNettButikkAsync(bool? direkteOrdre, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ordreFraNettRCResult>> ordreFraNettRCAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ordreFraNettRC_NYResult>> ordreFraNettRC_NYAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> proc_login_logAsync(string username, int? moduleID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<proc_restordreResult>> proc_restordreAsync(DateTime? datoFra, DateTime? datoTil, int? butikknr, string butikknavn, string ordreref, string ordreType, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<proc_restordre_linjeResult>> proc_restordre_linjeAsync(string ordreref, int? varenr, string varesok, int? butikknr, string butikknavn, string ordreType, bool? visAlleLinjer, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<proc_vareinfoResult>> proc_vareinfoAsync(string search, int? varenr, string varenrLev, string ean, bool? utenCSvarenr, byte? aktive, int? vgr1, int? vgr2, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<rc_salgstallResult>> rc_salgstallAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ReturImportFiler_VTFILER_RCResult>> ReturImportFiler_VTFILER_RCAsync(string filnavn, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SalgsprognoseResult>> SalgsprognoseAsync(int? antDagerPeriode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<salgstallResult>> salgstallAsync(int? rapptype, DateTime? datoFra, DateTime? datoTil, int? varenr, string varenrLev, string varetekst, bool? bestiltLevert, bool? ikkeLevert, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SendFakturaFil_2020Result>> SendFakturaFil_2020Async(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<swsg_regnskap_trigger_flyttingResult>> swsg_regnskap_trigger_flyttingAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Vareinfo_FasteDataResult>> Vareinfo_FasteDataAsync(int? id, decimal? utpris, decimal? innpris, decimal? NyNetto, decimal? estAndel, decimal? distrPris, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> vareinfo_updateAsync(int? id, int? varenr_swsg, string varenr_lev, string ean, string Varebeskrivelse_2, decimal? our_price, decimal? Innpris, decimal? Utpris, decimal? Utpris2, bool? Aktiv, int? vgr1, int? vgr2, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Vareinfo_VedlikeholdResult>> Vareinfo_VedlikeholdAsync(int? id, int? varenr_swn, string varenr_prod, string varenrLev, string ean, string varetekst, string sort, bool? aktiv, bool? utvid, bool? la, bool? lo, bool? se, bool? KJ, bool? SY, bool? TB, bool? TO, bool? FL, string productFit, bool? prøve, string bongtekst, string salgsnavn, string linkBilde, string linkforp, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<varetellingImportFilerResult>> varetellingImportFilerAsync(string filnavn, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<varetellingImportFiler_VTFILER_RCResult>> varetellingImportFiler_VTFILER_RCAsync(string filnavn, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
