// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CIS.Application.Legacy;

public partial class KonseptAntall
{
    public decimal Id { get; set; }

    public int? KonseptNr { get; set; }

    public int? VareId { get; set; }

    public int? Antall { get; set; }
}