// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CIS.DataAccess.Legacy;

public partial class Kundenrdato
{
    public decimal Id { get; set; }

    public int? Butikknr { get; set; }

    public int? Levid { get; set; }

    public int? Kundenr { get; set; }

    public DateOnly? Datofra { get; set; }

    public DateOnly? Datotil { get; set; }

    public int Aktiv { get; set; }
}