// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CIS.DataAccess.Legacy;

public partial class OrdreFraNett
{
    public decimal Id { get; set; }

    public int? OrdrenrNett { get; set; }

    public string VarenrLev { get; set; }

    public decimal? Antall { get; set; }

    public decimal? Frakt { get; set; }

    public int? Butikknr { get; set; }

    public bool? SendtLev { get; set; }

    public DateTime? DatoInserted { get; set; }

    public DateTime? DatoSendtLev { get; set; }

    public bool? Slettet { get; set; }

    public DateTime? DatoSlettet { get; set; }
}