// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CIS.Application.Legacy
{
    public partial class proc_restordre_linjeResult
    {
        [Column("ID", TypeName = "decimal(18,0)")]
        public decimal ID { get; set; }
        public int? Butikknr { get; set; }
        public string Butikknavn { get; set; }
        public string Ordreref { get; set; }
        public int? Varenr { get; set; }
        public string VarenrLev { get; set; }
        public string Varetekst { get; set; }
        public int OrdrAnt { get; set; }
        public int LevAnt { get; set; }
        public int? RestAnt { get; set; }
        [Column("Restverdi", TypeName = "decimal(29,8)")]
        public decimal? Restverdi { get; set; }
    }
}
