// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CIS.Application.Legacy;

public partial class TblCheckAutomate
{
    public byte? AmStatus { get; set; }

    public DateTime? Updated { get; set; }

    public bool? SendtMail { get; set; }
}