// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CIS.DataAccess.Legacy;

public partial class TblLoginLog
{
    public decimal Id { get; set; }

    public string Username { get; set; }

    public int? ModulId { get; set; }

    public DateTime? DateLogin { get; set; }
}