// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CIS.DataAccess.Legacy;

public partial class TblVaregr1
{
    public int IdVgr1 { get; set; }

    public string Varegruppe1 { get; set; }
}