// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CIS.DataAccess.Legacy;

public partial class TempImport1
{
    public int? LevVarenr { get; set; }

    public decimal? NyNetto { get; set; }

    public decimal? Andel { get; set; }

    public decimal? Kostpris { get; set; }
}