// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CIS.Application.Legacy;

public partial class VareinfoTemp2
{
    public string VarenrLev { get; set; }

    public string Varetekst { get; set; }
}