// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CIS.DataAccess.Legacy;

public partial class Varegruppe
{
    public int Varegruppenr { get; set; }

    public string Varegruppebeskrivelse { get; set; }
}