// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CIS.DataAccess.Legacy;

public partial class VareinfoBackup
{
    public decimal Id { get; set; }

    public int? VarenrSwn { get; set; }

    public string VarenrRc { get; set; }

    public string VarenrProd { get; set; }

    public string VarenrLev { get; set; }

    public string Ean { get; set; }

    public string Varebeskrivelse { get; set; }

    public string Varebeskrivelse2 { get; set; }

    public int? Varegruppenr { get; set; }

    public decimal? Innpris { get; set; }

    public decimal? Utpris { get; set; }

    public string SortKode { get; set; }

    public decimal? NyNetto { get; set; }

    public decimal? EstimertAndel { get; set; }

    public decimal? DistrKostpris { get; set; }

    public bool? Aktiv { get; set; }

    public DateTime? SistEndret { get; set; }

    public bool? ExportRc { get; set; }

    public bool? UtvidetSort { get; set; }

    public bool? La { get; set; }

    public bool? Lo { get; set; }

    public bool? Se { get; set; }

    public bool? Kj { get; set; }

    public bool? Sy { get; set; }

    public bool? Tb { get; set; }

    public bool? To { get; set; }

    public bool? Fl { get; set; }

    public string ProductFit { get; set; }

    public int? BongLengde { get; set; }

    public bool? Prøve { get; set; }

    public string Bongtekst { get; set; }

    public string LinkBildeBank { get; set; }

    public string LinkForpakning { get; set; }

    public string VaretekstAlternativ { get; set; }

    public decimal? OurPrice { get; set; }

    public decimal OurMarginKr { get; set; }

    public decimal? OurMarginP { get; set; }

    public decimal? MarginP { get; set; }

    public decimal? MarginKr { get; set; }
}