// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CIS.DataAccess.Legacy;

public partial class Varetelling
{
    public decimal Id { get; set; }

    public int? Butikknr { get; set; }

    public string VarenrLev { get; set; }

    public int? VareId { get; set; }

    public string Ean { get; set; }

    public string PeriodeRc { get; set; }

    public int? Antall { get; set; }

    public DateTime? Telledato { get; set; }
}