// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CIS.Application.Legacy;

public partial class Butikkliste
{
    public int Butikknr { get; set; }

    public string Butikknavn { get; set; }

    public string Gateadresse { get; set; }

    public int? Postnr { get; set; }

    public string Poststed { get; set; }

    public string Epost { get; set; }

    public int? Kjedenr { get; set; }

    public int? RegionNr { get; set; }

    public string RegionNavn { get; set; }

    public string Lokasjon { get; set; }

    public int? Konsept { get; set; }

    public bool? Aktiv { get; set; }

    public bool? KredittSperre { get; set; }

    public int? Kundenr { get; set; }

    public int? Telefon { get; set; }

    public DateTime? DatoSisteordre { get; set; }
}