// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CIS.Application.Legacy;

public partial class Ordre
{
    public decimal Id { get; set; }

    public DateTime? Dato { get; set; }

    public int? Butikknr { get; set; }

    public int? VareId { get; set; }

    public string VarenrLev { get; set; }

    public int? VarenrSwn { get; set; }

    public string Ean { get; set; }

    public int? Antall { get; set; }

    public int? AntallLevert { get; set; }

    public string Ordreref { get; set; }

    public byte? SendtLev { get; set; }

    public DateTime? Inserted { get; set; }

    public int? LevId { get; set; }

    public string Ordretype { get; set; }

    public DateTime? LevertDato { get; set; }

    public decimal? OurPrice { get; set; }

    public decimal? Innpris { get; set; }

    public string NettOrdreRef { get; set; }

    public int? Bedriftspakke { get; set; }
}