// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CIS.Application.Legacy
{
    public partial class proc_vareinfoResult
    {
        [Column("id", TypeName = "decimal(18,0)")]
        public decimal id { get; set; }
        public int Varenr { get; set; }
        public string VarenrLev { get; set; }
        public string EAN { get; set; }
        public string Varebeskrivelse { get; set; }
        public int? Vgr1 { get; set; }
        public string Varegruppe1 { get; set; }
        public int? Vgr2 { get; set; }
        public string Varegruppe2 { get; set; }
        [Column("InnprisCS", TypeName = "decimal(18,8)")]
        public decimal? InnprisCS { get; set; }
        [Column("MarginCS", TypeName = "decimal(18,8)")]
        public decimal? MarginCS { get; set; }
        [Column("MarginPCS", TypeName = "decimal(18,8)")]
        public decimal? MarginPCS { get; set; }
        [Column("InnprisRC", TypeName = "decimal(18,8)")]
        public decimal? InnprisRC { get; set; }
        [Column("UtprisRC", TypeName = "decimal(18,8)")]
        public decimal? UtprisRC { get; set; }
        [Column("MarginRC1Kr", TypeName = "decimal(18,8)")]
        public decimal? MarginRC1Kr { get; set; }
        [Column("MarginRC1P", TypeName = "decimal(18,8)")]
        public decimal? MarginRC1P { get; set; }
        [Column("UtprisRC2", TypeName = "decimal(18,8)")]
        public decimal? UtprisRC2 { get; set; }
        [Column("MarginRC2P", TypeName = "decimal(18,8)")]
        public decimal? MarginRC2P { get; set; }
        [Column("MarginRC2Kr", TypeName = "decimal(18,8)")]
        public decimal? MarginRC2Kr { get; set; }
        public bool? Aktiv { get; set; }
    }
}
