// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CIS.Application.Legacy;

public partial class Salg
{
    public decimal Id { get; set; }

    public int? Butikknr { get; set; }

    public DateTime? Dato { get; set; }

    public int? VareId { get; set; }

    public int? Antall { get; set; }

    public bool? SendFakt { get; set; }

    public int? Kundenr { get; set; }

    public int? Secbut { get; set; }

    public decimal? OurPrice { get; set; }

    public decimal? Innpris { get; set; }

    public decimal? Utpris { get; set; }

    public string VarenrLev { get; set; }

    public int? VarenrSwsg { get; set; }
}