// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CIS.Application.Legacy;

public partial class SwsgTooltip
{
    public decimal Id { get; set; }

    public string Modulnavn { get; set; }

    public string Tooltiptekst { get; set; }
}