// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CIS.Application.Legacy;

public partial class TblPostnr
{
    public string Postnr { get; set; }

    public string Poststed { get; set; }

    public int? Kommunenr { get; set; }

    public string Kommunenavn { get; set; }

    public string Kategori { get; set; }
}