// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CIS.Application.Legacy;

public partial class TblVaregr2
{
    public int IdVgr2 { get; set; }

    public string Varegruppe2 { get; set; }
}