// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CIS.Application.Legacy;

public partial class Vareinfo
{
    public decimal Id { get; set; }

    public int VarenrSwn { get; set; }

    public string VarenrLev { get; set; }

    public string Ean { get; set; }

    public string Varebeskrivelse2 { get; set; }

    public decimal? Innpris { get; set; }

    public decimal? Utpris { get; set; }

    public bool? Aktiv { get; set; }

    public DateTime? SistEndret { get; set; }

    public string VaretekstAlternativ { get; set; }

    public decimal? OurPrice { get; set; }

    public decimal? OurMarginKr { get; set; }

    public decimal? OurMarginP { get; set; }

    public decimal? MarginP { get; set; }

    public decimal? MarginKr { get; set; }

    public decimal? Utpris2 { get; set; }

    public decimal? MarginP2 { get; set; }

    public decimal? MarginKr2 { get; set; }

    public DateTime? DatoInserted { get; set; }

    public int? Vgr1 { get; set; }

    public int? Vgr2 { get; set; }
}