// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CIS.Application.Legacy;

public partial class VareinfoTemp
{
    public string VarenrLev { get; set; }

    public bool? Aktiv { get; set; }

    public bool? UtvidetSort { get; set; }

    public bool? La { get; set; }

    public bool? Lo { get; set; }

    public bool? Se { get; set; }

    public bool? Kj { get; set; }

    public bool? Sy { get; set; }

    public bool? Tb { get; set; }

    public bool? To { get; set; }

    public bool? Fl { get; set; }

    public string ProductFit { get; set; }

    public string Bongtekst { get; set; }

    public bool? Prøve { get; set; }

    public string LinkBildeBank { get; set; }

    public string LinkForpakning { get; set; }
}