name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]
    
jobs:
  integration-tests:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: "YourStrong!Passw0rd"
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Run integration tests
        run: dotnet test CIS.Tests.Integration --logger:trx --results-directory:TestResults --filter FullyQualifiedName~CIS.Tests.Integration

      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: TestResults
